"""""" Behaviour

syntax enable                             " Enable syntax highlighting
filetype on                               " Enable file type detection
filetype plugin on                        " Enable/load plugins for detected file type(s)
filetype indent on                        " Enable/load indent file for detected file type(s)
set noerrorbells                          " Disable error bells
set noswapfile                            " Disable the temporary swap files
set number                                " Add numbers to the side
set numberwidth=5                         " Make the number gutter 5 chars wide
set ruler                                 " Add the ruler for line/column details
set showcmd                               " Shows the command executed (or not, but it's harmless).
set cul                                   " Highlights the current line
set ignorecase                            " Search case-insensitive
set laststatus=2                          " Always show the statusline
set expandtab                             " Replace tabs with spaces
set tabstop=4                             " Replace each tab with 4 spaces
autocmd FileType yaml setlocal tabstop=2  " Replace each tab with 2 spaces for yaml
set wildmenu                              " Enable auto-complete menu on TAB
set wildmode=list:full                    " Auto-complete options sorting/style

"""""" Appearance

highlight LineNr term=underline ctermfg=Blue ctermbg=Black " Sets the line numbers to be blue with a black background
highlight StatusLine ctermfg=Blue ctermbg=White            " Sets the status line to blue with white text
