k9s:
  liveViewAutoRefresh: false
  refreshRate: 1
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: true
  ui: # NOTE! [K9s v0.30.0]
    skin: dracula
    enableMouse: true
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
  imageScans:
    enable: false
    exclusions:
      namespaces:
        - kube-system
      labels:
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreen: false
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
