if [ -f /usr/bin/vim ]; then
    export EDITOR=/usr/bin/vim
fi

if [ -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]; then
    export ZSH="$HOME/.oh-my-zsh"
    ZSH_THEME="robbyrussell"
    COMPLETION_WAITING_DOTS="true"
    plugins=(
        aliases                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aliases
        autojump                # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/autojump
        command-not-found       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/command-not-found
        gcloud                  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gcloud
        history                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/history
        thefuck                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/thefuck
        z                       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/z
        zsh-autosuggestions     # https://github.com/zsh-users/zsh-autosuggestions - manual download/installation in ../install.sh
        zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting/ - manual download/installation in ../install.sh
    )
    source "$ZSH/oh-my-zsh.sh"
fi

if [ -f "$HOME/.bash_aliases" ]; then
    mv "$HOME/.bash_aliases" "$HOME/.aliases"
fi

if [ -f "$HOME/.aliases" ]; then
    . "$HOME/.aliases"
fi

if [ -f "$HOME/.profile_extras" ]; then
    . "$HOME/.profile_extras"
fi
