HISTSIZE=1000000
SAVEHIST=1000000
HIST_STAMPS="yyyy-mm-dd"
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS # Ignore duplicates/purge earlier iterations
setopt HIST_IGNORE_SPACE    # Ignore lines starting with a space
setopt HIST_REDUCE_BLANKS   # Remove extra blanks from each line before saving
setopt SHARE_HISTORY        # Share history between sessions
export PIP_REQUIRE_VIRTUALENV=true

if [ -f "/usr/bin/vim" ]; then
    export EDITOR=/usr/bin/vim
fi

if [ -f "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if [ -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]; then
    export ZSH="$HOME/.oh-my-zsh"
    ZSH_THEME="ys"
    COMPLETION_WAITING_DOTS="true"
    plugins=(
        aliases                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aliases
        autojump                # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/autojump
        command-not-found       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/command-not-found
        gcloud                  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gcloud
        history                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/history
        thefuck                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/thefuck
        z                       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/z
        zsh-autosuggestions     # https://github.com/zsh-users/zsh-autosuggestions - manual download/installation in ../install.sh
        zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting/ - manual download/installation in ../install.sh
    )
    source "$ZSH/oh-my-zsh.sh"
fi

if [ -x "$(command -v starship)" ]; then

    if [ -f "$HOME/.config/starship.toml" ]; then
        eval "$(starship init zsh)"
    fi
fi

if [ -f "$HOME/.bash_aliases" ]; then
    mv "$HOME/.bash_aliases" "$HOME/.aliases"
fi

if [ -f "$HOME/.aliases" ]; then
    . "$HOME/.aliases"
fi

if [ -x "$(command -v fzf)" ]; then
    eval "$(fzf --zsh)"
    export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
fi

if [ -x "$(command -v rg)" ]; then
    export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
fi

if [ -f "$HOME/.profile_extras" ]; then
    . "$HOME/.profile_extras"
fi
