if [ -f /usr/bin/vim ]; then
    export EDITOR=/usr/bin/vim
fi

if [ -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]; then
    export ZSH="$HOME/.oh-my-zsh"
    ZSH_THEME="robbyrussell"
    COMPLETION_WAITING_DOTS="true"
    plugins=(
        autojump
        command-not-found
        gcloud
        history
        thefuck
        tmux
        zsh-autosuggestions
        z
    )
    source "$ZSH/oh-my-zsh.sh"
fi

if [ -f "$HOME/.bash_aliases" ]; then
    . "$HOME/.bash_aliases"
fi

if [ -f "$HOME/.profile_extras" ]; then
    . "$HOME/.profile_extras"
fi
