#!/bin/bash

alias ll='ls -alh'

# Adapted Windows habits
alias cls='clear'
alias dir='ls -al'
alias ii='open'
alias md='mkdir -p'

if [ -x "$(command -v bat)" ]; then
    alias cat='bat --plain'
fi

if [ -x "$(command -v lazydocker)" ]; then
    alias doc='lazydocker' # ld already exists
fi

if [ -x "$(command -v lsd)" ]; then
    alias ls='lsd'
    alias ll='lsd -alh'
    alias lt='lsd --tree'
else
    alias ll='ls -alh'
    alias lt='ls --tree'
fi

if [ -x "$(command -v git)" ]; then
    alias lg='lazygit'
fi

if [ -x "$(command -v terraform)" ]; then
    alias tff='terraform fmt'
    alias tfi='terraform init'
    alias tfp='terraform plan'
    alias tfv='terraform validate'
fi

if [ -x "$(command -v tmux)" ]; then
    alias attach='tmux attach -t'
fi

# Colours
if [ -x /usr/bin/dircolors ]; then
    test -r "$HOME/.dircolors" && eval "$(dircolors -b $HOME/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
