#!/bin/bash

# Adapted Windows habits
alias cls='clear'
alias dir='ls -al'
alias md='mkdir -p'

# Ansible
alias ans='ansible'
alias ans-c='ansible-config'
alias ans-i='ansible-inventory'
alias ans-p='ansible-playbook'

# General convenience and amusement
alias please='sudo'

# Colours
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi