#!/bin/bash

# Adapted Windows habits
alias cls='clear'
alias dir='ls -al'
alias ii='open'
alias md='mkdir -p'

# Terraform
alias tff='terraform format'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfv='terraform validate'

# tmux
alias attach='tmux attach -t'

# lazy apps
alias doc='lazydocker' # ld already exists
alias lg='lazygit'

# Colours
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [ -x "$(command -v bat)" ]; then
    alias cat='bat --paging=never'
fi
