#!/bin/bash
# For when I next look at this again and can't remember
# Vague defaults taken largely taken from /etc/skel/.bashrc
# Weird customisations my own

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoredups # Don't put duplicate lines or lines start with space in history.
HISTSIZE=1000
HISTFILESIZE=2000

# shopt settings
shopt -s histappend # Append to the history not overwrite.
shopt -s checkwinsize # Check and adjust window size on each command.

# Prompt
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

if [ -f "/usr/bin/vim" ]; then
    export EDITOR=/usr/bin/vim
fi

if [ -f "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if [ -x "$(command -v starship)" ]; then

    if [ -f "$HOME/.config/starship.toml" ]; then
        eval "$(starship init bash)"
    fi
fi

if [ -f "$HOME/.bash_aliases" ]; then
    mv "$HOME/.bash_aliases" "$HOME/.aliases"
fi

if [ -f "$HOME/.aliases" ]; then
    . "$HOME/.aliases"
fi

if [ -f "$HOME/.profile_extras" ]; then
    . "$HOME/.profile_extras"
fi

if [ -x "$(command -v fzf)" ]; then
    eval "$(fzf --bash)"
    export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
fi

if [ -x "$(command -v rg)" ]; then
    export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
fi
